/* ═══════════════════════════════════════════
   SUDOKU GAME — langs.js
   수정: 언어 추가/수정 시만 이 파일을 수정
   새 언어 추가 방법: LANG_LIST에 항목 추가 + TRANSLATIONS에 번역 추가
   ═══════════════════════════════════════════ */

// ── 언어 목록 (버튼으로 표시됨) ──
const LANG_LIST = [
  { code:'en', flag:'🇺🇸', name:'English'   },
  { code:'ko', flag:'🇰🇷', name:'한국어'     },
  { code:'ja', flag:'🇯🇵', name:'日本語'     },
  { code:'zh', flag:'🇨🇳', name:'中文'       },
  { code:'fr', flag:'🇫🇷', name:'Français'  },
  { code:'de', flag:'🇩🇪', name:'Deutsch'   },
  { code:'es', flag:'🇪🇸', name:'Español'   },
  { code:'pt', flag:'🇧🇷', name:'Português' },
  { code:'hi', flag:'🇮🇳', name:'हिन्दी'    },
  { code:'ar', flag:'🇸🇦', name:'العربية'   },
  { code:'ru', flag:'🇷🇺', name:'Русский'   },
  { code:'tr', flag:'🇹🇷', name:'Türkçe'    },
];

// ── 영어 기본값 (다른 언어에 없는 키는 영어로 대체됨) ──
const EN = {
  tagline:'Brain Training',
  'btn-new':'New Game',        'btn-new-s':'Choose difficulty and start',
  'btn-cont':'Continue',       'btn-cont-s':'Load saved file',
  'btn-rank':'Ranking',        'btn-rank-s':'View top scores',
  'btn-opt':'⚙️ Options',      'btn-opt-s':'Language & settings',
  'btn-how':'How to Play',     'btn-how-s':'Rules & controls',
  'dh':'⚙️ Difficulty',        'ds':'Choose your level',
  'easy':'Easy',   'easy-s':'5 hints · No penalty · 38–40 given · Unique answer',   'easy-tag':'EASY',
  'norm':'Normal', 'norm-s':'3 hints · −100 · 30–32 given · Unique answer',         'norm-tag':'NORMAL',
  'hard':'Hard',   'hard-s':'1 hint · −200 · 22–25 given · Unique answer',          'hard-tag':'HARD',
  'back':'← Back', 'home':'🏠 Menu',
  'lbl-t':'TIME','lbl-m':'MISS','lbl-sc':'SCORE','lbl-sk':'STREAK',
  'lbl-note':'Notes','lbl-er':'Erase','lbl-un':'Undo','lbl-pa':'Pause',
  'lbl-hint':'Use Hint','lbl-hl':' left','lbl-hp':'−200 pts',
  'lbl-save':'💾 Save','lbl-load':'📂 Load','ok':'OK',
  'cleared':'CLEAR!','retry':'↩ Retry','menu':'🏠 Menu',
  'retry2':'↩ Try Again','menu2':'🏠 Menu',
  'fail-t':'GAME OVER','fail-s':'3 mistakes! Try again.',
  'menu3':'🏠 Menu','restartall':'🔁 Restart',
  'all-s':'All stages complete!\nAmazing brain! 🧠',
  'pause-t':'PAUSED','pause-s':'Take a break!\nSave and exit if needed.',
  'resume':'▶ Resume','saveres':'💾 Save & Resume','menu4':'🏠 Menu',
  'load-t':'Save Found','load-ok':'📂 Load','cancel':'Cancel',
  'how-t':'How to Play',
  'how-b':'<b>📌 Rules</b><br>• Fill 9×9 grid with 1–9<br>• No repeats in row / col / 3×3 box<br>• ⚠️ Each difficulty has a COMPLETELY different puzzle!<br><br><b>🎮 Controls</b><br>• Click cell → click number<br>• Arrow keys · N: notes · Ctrl+Z: undo<br>• Ctrl+S: save · Esc: pause<br><br><b>⭐ Score</b><br>• Correct +100 · Streak bonus up to +300<br>• Mistake: penalty · Hint: −200',
  'gotit':'Got it!',
  'name-t':'YOUR NAME','name-s':'Enter name for ranking',
  'namesave':'Save Score','nameskip':'Skip',
  'clrr-t':'CLEAR?','clrr-s':'All ranking data will be deleted.',
  'clrr-yes':'Yes, Clear','clrr-no':'Cancel',
  'rank-t':'🏆 RANKING','rank-back':'← Back',
  'th-r':'#','th-p':'Player','th-sc':'Score','th-i':'Info','th-d':'Date',
  'clr-rank':'🗑️ Clear Rankings',
  'rank-empty':'No records yet. Play to set a score!',
  'rf-all':'All','rf-easy':'Easy','rf-norm':'Normal','rf-hard':'Hard',
  'stage':'Stage','next':'Next Stage →','final':'🏆 Final',
  'ct':'Time','cm':'Mistakes','ch':'Hints','ctb':'Time Bonus','cab':'Accuracy Bonus',
  'd-easy':'Easy','d-norm':'Normal','d-hard':'Hard',
  'ts-sel':'Select a cell first!','ts-fix':'Fixed number!',
  'ts-non':'✏️ Notes ON','ts-noff':'✏️ Notes OFF',
  'ts-un':'↩ Undone (−30)','ts-noun':'Nothing to undo',
  'ts-hint':'💡','ts-noemp':'No empty cells!',
  'ts-saved':'💾 Saved!','ts-lok':'📂 Loaded!',
  'ts-badf':'❌ Invalid save file','ts-readerr':'❌ Cannot read file',
  'ts-img':'🖼️ Image set!','num-done':'Complete! 🎉',
  'saved-ind':'✅ Saved','loaded-ind':'📂 Loaded',
  'stg-lbl':['Beginner','Intermediate','Advanced'],
  'rank-clrd':'Rankings cleared!',
};

// ── 번역 데이터 ──
// 주의: 없는 키는 자동으로 EN에서 가져옴
const TRANSLATIONS = {
  en: EN,

  ko:{
    tagline:'두뇌를 깨워라',
    'btn-new':'새 게임','btn-new-s':'난이도 선택 후 시작',
    'btn-cont':'이어하기','btn-cont-s':'저장 파일 불러오기',
    'btn-rank':'랭킹','btn-rank-s':'최고 점수 보기',
    'btn-opt':'⚙️ 옵션','btn-opt-s':'언어 및 설정',
    'btn-how':'게임 방법','btn-how-s':'규칙 & 조작법',
    'dh':'⚙️ 난이도 선택','ds':'난이도를 선택하세요',
    'easy':'쉬움','easy-s':'힌트 5개 · 감점 없음 · 38~40개 · 고유 정답','easy-tag':'EASY',
    'norm':'보통','norm-s':'힌트 3개 · 감점 −100 · 30~32개 · 고유 정답','norm-tag':'NORMAL',
    'hard':'어려움','hard-s':'힌트 1개 · 감점 −200 · 22~25개 · 고유 정답','hard-tag':'HARD',
    'back':'← 뒤로','home':'🏠 메인',
    'lbl-t':'시간','lbl-m':'실수','lbl-sc':'점수','lbl-sk':'연속',
    'lbl-note':'메모','lbl-er':'지우기','lbl-un':'되돌리기','lbl-pa':'일시정지',
    'lbl-hint':'힌트 사용','lbl-hl':'개 남음','lbl-hp':'점수 차감',
    'lbl-save':'💾 저장','lbl-load':'📂 불러오기','ok':'확인',
    'cleared':'CLEAR!','retry':'↩ 재도전','menu':'🏠 메인',
    'retry2':'↩ 다시 도전','menu2':'🏠 메인',
    'fail-t':'실패','fail-s':'실수 3번! 다시 도전하세요.',
    'menu3':'🏠 메인','restartall':'🔁 처음부터',
    'all-s':'모든 스테이지 완료!\n대단한 두뇌! 🧠',
    'pause-t':'일시정지','pause-s':'잠시 쉬어가세요!\n저장 후 나가도 됩니다.',
    'resume':'▶ 계속','saveres':'💾 저장 후 계속','menu4':'🏠 메인',
    'load-t':'저장 파일 발견','load-ok':'📂 이어하기','cancel':'취소',
    'how-t':'게임 방법',
    'how-b':'<b>📌 규칙</b><br>• 9×9 격자를 1~9로 채우기<br>• 행/열/3×3박스에 중복 금지<br>• ⚠️ 난이도마다 완전히 다른 퍼즐!<br><br><b>🎮 조작법</b><br>• 셀 클릭 → 숫자 클릭<br>• 방향키 이동 · N: 메모 · Ctrl+Z: 되돌리기<br>• Ctrl+S: 저장 · Esc: 일시정지<br><br><b>⭐ 점수</b><br>• 정답 +100 · 연속 보너스 최대 +300<br>• 오답 감점 · 힌트 −200',
    'gotit':'확인!',
    'name-t':'이름 입력','name-s':'랭킹에 등록할 이름을 입력하세요',
    'namesave':'점수 저장','nameskip':'건너뛰기',
    'clrr-t':'초기화?','clrr-s':'모든 랭킹 데이터가 삭제됩니다.',
    'clrr-yes':'네, 초기화','clrr-no':'취소',
    'rank-t':'🏆 랭킹','rank-back':'← 뒤로',
    'th-r':'순위','th-p':'이름','th-sc':'점수','th-i':'정보','th-d':'날짜',
    'clr-rank':'🗑️ 랭킹 초기화',
    'rank-empty':'아직 기록이 없습니다. 플레이하세요!',
    'rf-all':'전체','rf-easy':'쉬움','rf-norm':'보통','rf-hard':'어려움',
    'stage':'스테이지','next':'다음 스테이지 →','final':'🏆 최종',
    'ct':'시간','cm':'실수','ch':'힌트','ctb':'시간 보너스','cab':'정확도 보너스',
    'd-easy':'쉬움','d-norm':'보통','d-hard':'어려움',
    'ts-sel':'셀을 먼저 선택하세요!','ts-fix':'고정된 숫자예요!',
    'ts-non':'✏️ 메모 ON','ts-noff':'✏️ 메모 OFF',
    'ts-un':'↩ 되돌렸습니다 (−30)','ts-noun':'되돌릴 내용 없음',
    'ts-hint':'💡','ts-noemp':'빈 칸이 없어요!',
    'ts-saved':'💾 저장 완료!','ts-lok':'📂 불러오기 완료!',
    'ts-badf':'❌ 올바른 저장 파일이 아니에요','ts-readerr':'❌ 파일 읽기 실패',
    'ts-img':'🖼️ 이미지 설정 완료!','num-done':'완성! 🎉',
    'saved-ind':'✅ 저장됨','loaded-ind':'📂 불러옴',
    'stg-lbl':['입문','초급','고급'],
    'rank-clrd':'랭킹이 초기화되었습니다!',
  },

  ja:{
    tagline:'脳トレ',
    'btn-new':'新しいゲーム','btn-new-s':'難易度を選んでスタート',
    'btn-cont':'続きから','btn-cont-s':'保存ファイルを読み込む',
    'btn-rank':'ランキング','btn-rank-s':'最高スコアを見る',
    'btn-opt':'⚙️ オプション','btn-opt-s':'言語と設定',
    'btn-how':'遊び方','btn-how-s':'ルールと操作方法',
    'dh':'⚙️ 難易度','ds':'難易度を選んでください',
    'easy':'かんたん','easy-s':'ヒント5個・減点なし・38–40個・固有の解答','easy-tag':'EASY',
    'norm':'ふつう','norm-s':'ヒント3個・減点−100・30–32個・固有の解答','norm-tag':'NORMAL',
    'hard':'むずかしい','hard-s':'ヒント1個・減点−200・22–25個・固有の解答','hard-tag':'HARD',
    'back':'← 戻る','home':'🏠 メイン',
    'lbl-t':'時間','lbl-m':'ミス','lbl-sc':'スコア','lbl-sk':'連続',
    'lbl-note':'メモ','lbl-er':'削除','lbl-un':'元に戻す','lbl-pa':'一時停止',
    'lbl-hint':'ヒント','lbl-hl':'個残り','lbl-hp':'点数減少',
    'lbl-save':'💾 保存','lbl-load':'📂 読込','ok':'確認',
    'cleared':'クリア！','retry':'↩ リトライ','menu':'🏠 メイン',
    'retry2':'↩ もう一度','menu2':'🏠 メイン',
    'fail-t':'ゲームオーバー','fail-s':'3回ミス！もう一度挑戦してください。',
    'menu3':'🏠 メイン','restartall':'🔁 最初から',
    'all-s':'全ステージクリア！\nすごい脳力！🧠',
    'pause-t':'一時停止','pause-s':'休憩しよう！\n保存して終了できます。',
    'resume':'▶ 再開','saveres':'💾 保存して再開','menu4':'🏠 メイン',
    'load-t':'セーブデータ発見','load-ok':'📂 読み込む','cancel':'キャンセル',
    'how-t':'遊び方',
    'how-b':'<b>📌 ルール</b><br>• 9×9のマスを1〜9で埋める<br>• 行/列/3×3ブロック内で重複禁止<br>• ⚠️ 難易度ごとに全く異なるパズル！<br><br><b>🎮 操作</b><br>• マスをクリック → 数字ボタン<br>• 矢印キーで移動 · N: メモ · Ctrl+Z: 元に戻す<br>• Ctrl+S: 保存 · Esc: 停止<br><br><b>⭐ スコア</b><br>• 正解+100・連続最大+300<br>• 不正解: 減点 · ヒント −200',
    'gotit':'わかった！',
    'name-t':'名前入力','name-s':'ランキング登録用の名前を入力',
    'namesave':'スコア保存','nameskip':'スキップ',
    'clrr-t':'クリア？','clrr-s':'全てのランキングデータが削除されます。',
    'clrr-yes':'はい、クリア','clrr-no':'キャンセル',
    'rank-t':'🏆 ランキング','rank-back':'← 戻る',
    'th-r':'順位','th-p':'名前','th-sc':'スコア','th-i':'情報','th-d':'日付',
    'clr-rank':'🗑️ ランキングをクリア',
    'rank-empty':'まだ記録がありません。プレイしましょう！',
    'rf-all':'全て','rf-easy':'かんたん','rf-norm':'ふつう','rf-hard':'むずかしい',
    'stage':'ステージ','next':'次のステージ →','final':'🏆 最終',
    'ct':'時間','cm':'ミス','ch':'ヒント','ctb':'タイムボーナス','cab':'正確さボーナス',
    'd-easy':'かんたん','d-norm':'ふつう','d-hard':'むずかしい',
    'ts-sel':'マスを選んでください！','ts-fix':'固定された数字です！',
    'ts-non':'✏️ メモ ON','ts-noff':'✏️ メモ OFF',
    'ts-un':'↩ 元に戻しました (−30)','ts-noun':'戻せる操作がありません',
    'ts-hint':'💡','ts-noemp':'空きマスがありません！',
    'ts-saved':'💾 保存しました！','ts-lok':'📂 読み込みました！',
    'ts-badf':'❌ 正しいセーブファイルではありません','ts-readerr':'❌ ファイルを読み込めません',
    'ts-img':'🖼️ 画像を設定しました！','num-done':'完成！🎉',
    'saved-ind':'✅ 保存済み','loaded-ind':'📂 読込済み',
    'stg-lbl':['初級','中級','上級'],
    'rank-clrd':'ランキングをクリアしました！',
  },

  zh:{
    tagline:'大脑训练',
    'btn-new':'新游戏','btn-new-s':'选择难度开始',
    'btn-cont':'继续游戏','btn-cont-s':'加载保存文件',
    'btn-rank':'排行榜','btn-rank-s':'查看最高分',
    'btn-opt':'⚙️ 选项','btn-opt-s':'语言和设置',
    'btn-how':'游戏说明','btn-how-s':'规则和操作',
    'dh':'⚙️ 选择难度','ds':'请选择难度',
    'easy':'简单','easy-s':'5个提示·无扣分·38–40个数字·独特答案','easy-tag':'EASY',
    'norm':'普通','norm-s':'3个提示·扣分−100·30–32个数字·独特答案','norm-tag':'NORMAL',
    'hard':'困难','hard-s':'1个提示·扣分−200·22–25个数字·独特答案','hard-tag':'HARD',
    'back':'← 返回','home':'🏠 主菜单',
    'lbl-t':'时间','lbl-m':'失误','lbl-sc':'分数','lbl-sk':'连续',
    'lbl-note':'笔记','lbl-er':'删除','lbl-un':'撤销','lbl-pa':'暂停',
    'lbl-hint':'使用提示','lbl-hl':'个剩余','lbl-hp':'扣分',
    'lbl-save':'💾 保存','lbl-load':'📂 加载','ok':'确认',
    'cleared':'通关！','retry':'↩ 重试','menu':'🏠 主菜单',
    'retry2':'↩ 再试','menu2':'🏠 主菜单',
    'fail-t':'失败','fail-s':'3次失误！请重试。',
    'menu3':'🏠 主菜单','restartall':'🔁 重新开始',
    'all-s':'所有关卡完成！\n厉害的大脑！🧠',
    'pause-t':'已暂停','pause-s':'休息一下！\n可以保存后退出。',
    'resume':'▶ 继续','saveres':'💾 保存并继续','menu4':'🏠 主菜单',
    'load-t':'找到存档','load-ok':'📂 加载','cancel':'取消',
    'how-t':'游戏说明',
    'how-b':'<b>📌 规则</b><br>• 用1-9填满9×9格<br>• 行/列/3×3格内不重复<br>• ⚠️ 每种难度都有完全不同的谜题！<br><br><b>🎮 操作</b><br>• 点击格子→点击数字<br>• 方向键移动·N: 笔记·Ctrl+Z: 撤销<br>• Ctrl+S: 保存·Esc: 暂停<br><br><b>⭐ 得分</b><br>• 正确+100·连续最高+300<br>• 错误扣分·提示 −200',
    'gotit':'明白了！',
    'name-t':'输入名字','name-s':'输入排行榜显示的名字',
    'namesave':'保存分数','nameskip':'跳过',
    'clrr-t':'清除？','clrr-s':'所有排行榜数据将被删除。',
    'clrr-yes':'是，清除','clrr-no':'取消',
    'rank-t':'🏆 排行榜','rank-back':'← 返回',
    'th-r':'名次','th-p':'名字','th-sc':'分数','th-i':'信息','th-d':'日期',
    'clr-rank':'🗑️ 清除排行榜','rank-empty':'暂无记录，快去游戏吧！',
    'rf-all':'全部','rf-easy':'简单','rf-norm':'普通','rf-hard':'困难',
    'stage':'关卡','next':'下一关 →','final':'🏆 最终',
    'ct':'时间','cm':'失误','ch':'提示','ctb':'时间奖励','cab':'准确度奖励',
    'd-easy':'简单','d-norm':'普通','d-hard':'困难',
    'ts-sel':'请先选择格子！','ts-fix':'固定数字！',
    'ts-non':'✏️ 笔记 开','ts-noff':'✏️ 笔记 关',
    'ts-un':'↩ 已撤销 (−30)','ts-noun':'没有可撤销内容',
    'ts-hint':'💡','ts-noemp':'没有空格！',
    'ts-saved':'💾 保存成功！','ts-lok':'📂 加载成功！',
    'ts-badf':'❌ 无效存档','ts-readerr':'❌ 无法读取',
    'ts-img':'🖼️ 图片已设置！','num-done':'完成！🎉',
    'saved-ind':'✅ 已保存','loaded-ind':'📂 已加载',
    'stg-lbl':['初级','中级','高级'],'rank-clrd':'排行榜已清除！',
  },

  fr:{
    tagline:'Entraînement cérébral',
    'btn-new':'Nouvelle Partie','btn-new-s':'Choisir la difficulté',
    'btn-cont':'Continuer','btn-cont-s':'Charger une sauvegarde',
    'btn-rank':'Classement','btn-rank-s':'Meilleurs scores',
    'btn-opt':'⚙️ Options','btn-opt-s':'Langue et paramètres',
    'btn-how':'Comment jouer','btn-how-s':'Règles et commandes',
    'dh':'⚙️ Difficulté','ds':'Choisissez votre niveau',
    'easy':'Facile','easy-s':'5 indices · Sans pénalité · 38–40 chiffres · Solution unique','easy-tag':'EASY',
    'norm':'Normal','norm-s':'3 indices · −100 · 30–32 chiffres · Solution unique','norm-tag':'NORMAL',
    'hard':'Difficile','hard-s':'1 indice · −200 · 22–25 chiffres · Solution unique','hard-tag':'HARD',
    'back':'← Retour','home':'🏠 Menu',
    'lbl-t':'TEMPS','lbl-m':'ERREURS','lbl-sc':'SCORE','lbl-sk':'SÉRIE',
    'lbl-note':'Notes','lbl-er':'Effacer','lbl-un':'Annuler','lbl-pa':'Pause',
    'lbl-hint':'Indice','lbl-hl':' restants','lbl-hp':'−200 pts',
    'lbl-save':'💾 Sauvegarder','lbl-load':'📂 Charger','ok':'OK',
    'cleared':'RÉUSSI!','retry':'↩ Réessayer','menu':'🏠 Menu',
    'retry2':'↩ Réessayer','menu2':'🏠 Menu',
    'fail-t':'ÉCHEC','fail-s':'3 erreurs! Réessayez.',
    'menu3':'🏠 Menu','restartall':'🔁 Recommencer',
    'all-s':'Tous les niveaux terminés!\nCerveau incroyable! 🧠',
    'pause-t':'PAUSE','pause-s':'Reposez-vous!\nSauvegardez si nécessaire.',
    'resume':'▶ Reprendre','saveres':'💾 Sauvegarder & Reprendre','menu4':'🏠 Menu',
    'load-t':'Sauvegarde trouvée','load-ok':'📂 Charger','cancel':'Annuler',
    'how-t':'Comment jouer',
    'how-b':'<b>📌 Règles</b><br>• Remplir 9×9 avec 1–9<br>• Pas de répétition ligne/colonne/carré<br>• ⚠️ Chaque difficulté a un puzzle différent!<br><br><b>🎮 Commandes</b><br>• Cliquer cellule → chiffre · Flèches pour déplacer<br>• N: notes · Ctrl+Z: annuler · Esc: pause<br><br><b>⭐ Score</b><br>• Correct +100 · Série max +300<br>• Erreur: pénalité · Indice: −200',
    'gotit':'Compris!',
    'name-t':'VOTRE NOM','name-s':'Entrez votre nom pour le classement',
    'namesave':'Sauvegarder','nameskip':'Passer',
    'clrr-t':'EFFACER?','clrr-s':'Toutes les données seront supprimées.',
    'clrr-yes':'Oui, effacer','clrr-no':'Annuler',
    'rank-t':'🏆 CLASSEMENT','rank-back':'← Retour',
    'th-r':'#','th-p':'Joueur','th-sc':'Score','th-i':'Info','th-d':'Date',
    'clr-rank':'🗑️ Effacer classement','rank-empty':'Pas encore de records!',
    'rf-all':'Tout','rf-easy':'Facile','rf-norm':'Normal','rf-hard':'Difficile',
    'stage':'Niveau','next':'Niveau suivant →','final':'🏆 Final',
    'ct':'Temps','cm':'Erreurs','ch':'Indices','ctb':'Bonus temps','cab':'Bonus précision',
    'd-easy':'Facile','d-norm':'Normal','d-hard':'Difficile',
    'stg-lbl':['Débutant','Intermédiaire','Avancé'],'rank-clrd':'Classement effacé!',
  },

  de:{
    tagline:'Gehirntraining',
    'btn-new':'Neues Spiel','btn-new-s':'Schwierigkeit wählen und starten',
    'btn-cont':'Fortfahren','btn-cont-s':'Spielstand laden',
    'btn-rank':'Rangliste','btn-rank-s':'Beste Punkte',
    'btn-opt':'⚙️ Optionen','btn-opt-s':'Sprache und Einstellungen',
    'btn-how':'Anleitung','btn-how-s':'Regeln und Steuerung',
    'dh':'⚙️ Schwierigkeit','ds':'Wählen Sie Ihren Level',
    'easy':'Leicht','easy-s':'5 Hinweise · Keine Strafe · 38–40 Zahlen · Einzigartige Lösung','easy-tag':'EASY',
    'norm':'Mittel','norm-s':'3 Hinweise · −100 · 30–32 Zahlen · Einzigartige Lösung','norm-tag':'NORMAL',
    'hard':'Schwer','hard-s':'1 Hinweis · −200 · 22–25 Zahlen · Einzigartige Lösung','hard-tag':'HARD',
    'back':'← Zurück','home':'🏠 Menü',
    'lbl-t':'ZEIT','lbl-m':'FEHLER','lbl-sc':'PUNKTE','lbl-sk':'SERIE',
    'lbl-note':'Notizen','lbl-er':'Löschen','lbl-un':'Rückgängig','lbl-pa':'Pause',
    'fail-t':'SPIEL VORBEI','fail-s':'3 Fehler! Versuchen Sie es erneut.',
    'all-s':'Alle Level geschafft!\nGehirn-Champion! 🧠',
    'stg-lbl':['Anfänger','Mittelstufe','Fortgeschritten'],'rank-clrd':'Rangliste gelöscht!',
  },

  es:{
    tagline:'Entrenamiento cerebral',
    'btn-new':'Nuevo Juego','btn-new-s':'Elegir dificultad y empezar',
    'btn-cont':'Continuar','btn-cont-s':'Cargar archivo guardado',
    'btn-rank':'Clasificación','btn-rank-s':'Ver mejores puntuaciones',
    'btn-opt':'⚙️ Opciones','btn-opt-s':'Idioma y ajustes',
    'btn-how':'Cómo jugar','btn-how-s':'Reglas y controles',
    'dh':'⚙️ Dificultad','ds':'Elige tu nivel',
    'easy':'Fácil','easy-s':'5 pistas · Sin penalización · 38–40 números · Solución única','easy-tag':'EASY',
    'norm':'Normal','norm-s':'3 pistas · −100 · 30–32 números · Solución única','norm-tag':'NORMAL',
    'hard':'Difícil','hard-s':'1 pista · −200 · 22–25 números · Solución única','hard-tag':'HARD',
    'back':'← Volver','home':'🏠 Menú',
    'lbl-t':'TIEMPO','lbl-m':'ERRORES','lbl-sc':'PUNTOS','lbl-sk':'RACHA',
    'fail-t':'FALLIDO','fail-s':'¡3 errores! Inténtalo de nuevo.',
    'all-s':'¡Todos los niveles completos!\n¡Cerebro increíble! 🧠',
    'stg-lbl':['Principiante','Intermedio','Avanzado'],'rank-clrd':'¡Clasificación borrada!',
  },

  pt:{
    tagline:'Treinamento cerebral',
    'btn-new':'Novo Jogo','btn-new-s':'Escolher dificuldade e começar',
    'btn-cont':'Continuar','btn-cont-s':'Carregar jogo salvo',
    'btn-rank':'Classificação','btn-rank-s':'Melhores pontuações',
    'btn-opt':'⚙️ Opções','btn-opt-s':'Idioma e configurações',
    'btn-how':'Como jogar','btn-how-s':'Regras e controles',
    'dh':'⚙️ Dificuldade','ds':'Escolha seu nível',
    'easy':'Fácil','easy-s':'5 dicas · Sem penalidade · 38–40 números · Solução única','easy-tag':'EASY',
    'norm':'Normal','norm-s':'3 dicas · −100 · 30–32 números · Solução única','norm-tag':'NORMAL',
    'hard':'Difícil','hard-s':'1 dica · −200 · 22–25 números · Solução única','hard-tag':'HARD',
    'back':'← Voltar','home':'🏠 Menu',
    'lbl-t':'TEMPO','lbl-m':'ERROS','lbl-sc':'PONTOS','lbl-sk':'SEQUÊNCIA',
    'fail-t':'FALHOU','fail-s':'3 erros! Tente novamente.',
    'all-s':'Todos os níveis completos!\nCérebro incrível! 🧠',
    'stg-lbl':['Iniciante','Intermediário','Avançado'],'rank-clrd':'Classificação limpa!',
  },

  hi:{
    tagline:'मस्तिष्क प्रशिक्षण',
    'btn-new':'नया खेल','btn-new-s':'कठिनाई चुनें और शुरू करें',
    'btn-cont':'जारी रखें','btn-cont-s':'सहेजी फ़ाइल लोड करें',
    'btn-rank':'रैंकिंग','btn-rank-s':'शीर्ष स्कोर',
    'btn-opt':'⚙️ विकल्प','btn-opt-s':'भाषा और सेटिंग',
    'btn-how':'कैसे खेलें','btn-how-s':'नियम और नियंत्रण',
    'dh':'⚙️ कठिनाई','ds':'अपना स्तर चुनें',
    'easy':'आसान','easy-s':'5 संकेत · जुर्माना नहीं · 38–40 · अद्वितीय हल','easy-tag':'EASY',
    'norm':'सामान्य','norm-s':'3 संकेत · −100 · 30–32 · अद्वितीय हल','norm-tag':'NORMAL',
    'hard':'कठिन','hard-s':'1 संकेत · −200 · 22–25 · अद्वितीय हल','hard-tag':'HARD',
    'back':'← वापस','home':'🏠 मेनू',
    'fail-t':'असफल','fail-s':'3 गलतियां! फिर प्रयास करें।',
    'all-s':'सभी चरण पूर्ण!\nशानदार दिमाग! 🧠',
    'stg-lbl':['शुरुआत','मध्यवर्ती','उन्नत'],'rank-clrd':'रैंकिंग साफ़!',
  },

  ar:{
    tagline:'تدريب الدماغ',
    'btn-new':'لعبة جديدة','btn-new-s':'اختر الصعوبة وابدأ',
    'btn-cont':'متابعة','btn-cont-s':'تحميل ملف محفوظ',
    'btn-rank':'التصنيف','btn-rank-s':'أفضل النقاط',
    'btn-opt':'⚙️ خيارات','btn-opt-s':'اللغة والإعدادات',
    'btn-how':'كيفية اللعب','btn-how-s':'القواعد والتحكم',
    'dh':'⚙️ الصعوبة','ds':'اختر مستواك',
    'easy':'سهل','easy-s':'5 تلميحات · بدون عقوبة · 38–40 رقماً · حل فريد','easy-tag':'EASY',
    'norm':'عادي','norm-s':'3 تلميحات · −100 · 30–32 رقماً · حل فريد','norm-tag':'NORMAL',
    'hard':'صعب','hard-s':'1 تلميح · −200 · 22–25 رقماً · حل فريد','hard-tag':'HARD',
    'back':'← رجوع','home':'🏠 القائمة',
    'fail-t':'فشل','fail-s':'3 أخطاء! حاول مجدداً.',
    'all-s':'تمت جميع المراحل!\nعقل رائع! 🧠',
    'stg-lbl':['مبتدئ','متوسط','متقدم'],'rank-clrd':'تم مسح التصنيف!',
  },

  ru:{
    tagline:'Тренировка мозга',
    'btn-new':'Новая Игра','btn-new-s':'Выбрать сложность и начать',
    'btn-cont':'Продолжить','btn-cont-s':'Загрузить сохранение',
    'btn-rank':'Рейтинг','btn-rank-s':'Лучшие результаты',
    'btn-opt':'⚙️ Настройки','btn-opt-s':'Язык и параметры',
    'btn-how':'Как играть','btn-how-s':'Правила и управление',
    'dh':'⚙️ Сложность','ds':'Выберите уровень',
    'easy':'Лёгкий','easy-s':'5 подсказок · Без штрафов · 38–40 цифр · Уникальное решение','easy-tag':'EASY',
    'norm':'Средний','norm-s':'3 подсказки · −100 · 30–32 цифры · Уникальное решение','norm-tag':'NORMAL',
    'hard':'Сложный','hard-s':'1 подсказка · −200 · 22–25 цифр · Уникальное решение','hard-tag':'HARD',
    'back':'← Назад','home':'🏠 Меню',
    'lbl-t':'ВРЕМЯ','lbl-m':'ОШИБКИ','lbl-sc':'ОЧКИ','lbl-sk':'СЕРИЯ',
    'fail-t':'ИГРА ОКОНЧЕНА','fail-s':'3 ошибки! Попробуйте снова.',
    'all-s':'Все уровни пройдены!\nГениальный мозг! 🧠',
    'stg-lbl':['Начинающий','Средний','Продвинутый'],'rank-clrd':'Рейтинг очищен!',
  },

  tr:{
    tagline:'Beyin Antrenmanı',
    'btn-new':'Yeni Oyun','btn-new-s':'Zorluk seç ve başla',
    'btn-cont':'Devam Et','btn-cont-s':'Kayıtlı dosya yükle',
    'btn-rank':'Sıralama','btn-rank-s':'En yüksek puanlar',
    'btn-opt':'⚙️ Seçenekler','btn-opt-s':'Dil ve ayarlar',
    'btn-how':'Nasıl Oynanır','btn-how-s':'Kurallar ve kontroller',
    'dh':'⚙️ Zorluk','ds':'Seviyenizi seçin',
    'easy':'Kolay','easy-s':'5 ipucu · Ceza yok · 38–40 sayı · Benzersiz çözüm','easy-tag':'EASY',
    'norm':'Orta','norm-s':'3 ipucu · −100 · 30–32 sayı · Benzersiz çözüm','norm-tag':'NORMAL',
    'hard':'Zor','hard-s':'1 ipucu · −200 · 22–25 sayı · Benzersiz çözüm','hard-tag':'HARD',
    'back':'← Geri','home':'🏠 Menü',
    'lbl-t':'SÜRE','lbl-m':'HATA','lbl-sc':'PUAN','lbl-sk':'SERİ',
    'fail-t':'OYUN BİTTİ','fail-s':'3 hata! Tekrar deneyin.',
    'all-s':'Tüm bölümler tamamlandı!\nMüthiş beyin! 🧠',
    'stg-lbl':['Başlangıç','Orta','İleri'],'rank-clrd':'Sıralama temizlendi!',
  },
};

// ── 없는 키 자동으로 영어로 채우기 ──
Object.keys(TRANSLATIONS).forEach(lang => {
  if (lang === 'en') return;
  Object.keys(EN).forEach(k => {
    if (!(k in TRANSLATIONS[lang])) TRANSLATIONS[lang][k] = EN[k];
  });
});

// ── T() 함수: 현재 언어에서 텍스트 가져오기 ──
let curLang = 'en';
function T(k) {
  return (TRANSLATIONS[curLang] || EN)[k] || EN[k] || k;
}
